// Top-level build file where you can add configuration options common to all sub-projects/modules.

apply plugin: 'idea'

buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://maven.fabric.io/public' }
        jcenter() // Deprecated but kept for legacy dependencies
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.1'
        // classpath 'de.felixschulze.gradle:gradle-hockeyapp-plugin:3.6' // HockeyApp deprecated
        // classpath 'io.fabric.tools:gradle:1.+' // Fabric deprecated
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://www.jitpack.io' }
        maven { url 'https://maven.fabric.io/public' }
        jcenter() // Deprecated but kept for legacy dependencies
    }
}
